version: "3.4"

services:
  ansible-host:
    container_name: ansible-host
    image: khoanguyen1507/ansible-host-image:develop
    build: 
      context: .
      dockerfile: Dockerfile
      target: host
    networks:
      ansible-net:
        ipv4_address: 172.24.0.4
    volumes:
      - /Users/mac/Documents/DayThem/BK1.DevOpsonline/L7/data:/root/workspace/data
  ansible-node-1:
    container_name: ansible-node-1
    image: khoanguyen1507/ansible-node-image:node-1
    build: 
      context: .
      dockerfile: Dockerfile
      target: node
    networks:
      ansible-net:
        ipv4_address: 172.24.0.3
  ansible-node-2:
    container_name: ansible-node-2
    image: khoanguyen1507/ansible-node-image:node-1
    build: 
      context: .
      dockerfile: Dockerfile
      target: node
    networks:
      ansible-net:
        ipv4_address: 172.24.0.2
networks:
  ansible-net:
    ipam:
      config:
        - subnet: 172.24.0.0/24
  
